#!/bin/sh

# Start functions
# $1: install_path
# $2: file name 
# $3: link name (optional)
install_dep(){
  install_path=$1
  lib_name=$2
  link_name=$3
  
  if [ ! -e "$install_path/$lib_name" ];
  then
    echo "$lib_name not found. It will be installed"
    cp $lib_name $install_path
    # if the link name is not empty
    if [ "x$link_name" != "x" ]; then
      echo "linking $lib_name to $link_name"
      ln -s $install_path/$lib_name $install_path/$link_name
    fi
  else
    echo "$lib_name found"
  fi
}

# Print out the help
usage(){
    echo "usage: install -s SRC_FOLDER | [[-h]]"
}
# End functions 

PORTNAME=linux-makemkv-lite
PORTVERSION=1.9.10
CATEGORIES=multimedia
LINUXBASE=/compat/linux
SRC_FOLDER=/usr/ports/multimedia/$PORTNAME
DESTDIR=
PREFIX=usr
INSTALLL_DIR=/$PREFIX/local/bin
ulib=$LINUXBASE/$PREFIX/lib
llib=$LINUXBASE/lib

while [ "$1" != "" ]; do
    case $1 in
        -s | --source-folder )	shift
                                SRC_FOLDER=$1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

echo **************************
echo *** Installing MakeMKV ***
echo **************************

# requires: linux_base-c6
# run  pkg install linux_base-c6 
pkg install linux_base-c6

echo "Installing oss part..."
cd $SRC_FOLDER/oss

for i in libdriveio.so.0 libmakemkv.so.1 libmmbd.so.0
do
  echo "Copying" $i "under" $LINUXBASE/lib 
  cp $i $LINUXBASE/lib
done

cp makemkv-lite $INSTALLL_DIR/makemkv-lite
chmod +x $INSTALLL_DIR/makemkv-lite
cp play-stream $INSTALLL_DIR/
chmod +x $INSTALLL_DIR/play-stream

echo "Installing bin part..."
cd $SRC_FOLDER/bin/i386
echo "Copying" $SRC_FOLDER/bin/i386 "under" $LINUXBASE/$PREFIX/bin
cp -r $SRC_FOLDER/bin/i386/. $LINUXBASE/$PREFIX/bin
chmod +x $LINUXBASE/$PREFIX/bin/makemkvcon

cd $SRC_FOLDER/bin/extra
echo "Copying" $SRC_FOLDER/bin/extra "under" $INSTALLL_DIR
cp -r $SRC_FOLDER/bin/extra/. $INSTALLL_DIR/
chmod +x $INSTALLL_DIR/update-aacs-keys
#TODO: update-license-key
#chmod +x $INSTALLL_DIR/update-license-key

cd $SRC_FOLDER/bin/share
mkdir -p $LINUXBASE/$PREFIX/share/MakeMKV
cp -r  $SRC_FOLDER/bin/share/. $LINUXBASE/$PREFIX/share/MakeMKV

# decryption keys to be fetched from http://vlc-bluray.whoknowsmy.name/
echo "Fetching AACS Keys..."
curl -o /tmp/KEYDB.cfg http://www.labdv.com/aacs/KEYDB.cfg
cp /tmp/KEYDB.cfg $LINUXBASE/$PREFIX/share/MakeMKV/KEYDB.cfg

# libexpat.so.1 (/compat/linux/lib)
pkg install linux-c6-expat

echo "Checking extra lib dependencies for makemkvcon..."
cd $SRC_FOLDER/bin/lib

# libcrypto.so.10
install_dep $ulib libcrypto.so.1.0.1e libcrypto.so.10
# libavcodec.so.53 
install_dep $ulib libavcodec.so.53.61.100 libavcodec.so.53
# libavutil.so.51
install_dep $ulib libavutil.so.51.35.100 libavutil.so.51
# libva.so.1
install_dep $ulib libva.so.1.3801.0 libva.so.1
# libxvidcore.so.4 
install_dep $ulib libxvidcore.so.4.3 libxvidcore.so.4
# libx264.so.120 
install_dep $ulib libx264.so.120

# libvorbisenc.so.2 
# libvorbis.so.0 
pkg install linux-c6-libvorbis

# libtheoraenc.so.1 
# libtheoradec.so.1 
pkg install linux-c6-libtheora

# libspeex.so.1 
install_dep $ulib libspeex.so.1.5.0 libspeex.so.1
# libschroedinger-1.0.so.0 
install_dep $ulib libschroedinger-1.0.so.0.2.0 libschroedinger-1.0.so.0
# libopenjpeg.so.2 
install_dep $ulib libopenjpeg.so.2.1.3.0 libopenjpeg.so.2
# libmp3lame.so.0 
install_dep $ulib libmp3lame.so.0.0.0 libmp3lame.so.0
# libgsm.so.1 
install_dep $ulib libgsm.so.1.0.12 libgsm.so.1
# libcelt0.so.1 
install_dep $ulib libcelt0.so.1.0.0 libcelt0.so.1
# libogg.so.0 
install_dep $ulib libogg.so.0.6.0 libogg.so.0
# liboil-0.3.so.0
install_dep $ulib liboil-0.3.so.0

#echo "Symlinking makemkv"
#ln -s $LINUXBASE/$PREFIX/bin/makemkv $INSTALLL_DIR/makemkv

#echo "Symlinking makemkv-lite"
#ln -s $LINUXBASE/$PREFIX/bin/makemkv-lite $INSTALLL_DIR/makemkv-lite

echo "Symlinking makemkvcon"
ln -s $LINUXBASE/$PREFIX/bin/makemkvcon $INSTALLL_DIR/makemkvcon

echo "Creating MakeMKV root directory"
mkdir -p /root/.MakeMKV && cp /tmp/KEYDB.cfg /root/.MakeMKV/KEYDB.cfg

echo ****************************************
echo **************** INFO ******************
echo ****************************************
echo *** Please run MakeMKV as root user  ***
echo ****************************************

echo Press any key to close the installer...
read dummy
